-- Initialize everything
require('config.setup')
require('config.plugins')
require('config.vimspector')
require('config.todo-comments')
require('config.mappings')
require('config.lualine')
require('config.language-servers')
require('config.gitsigns')
require('config.telescope')
require('config.nerdtree')
require('config.completion')
require('config.treesitter')
require('config.leap')
require('config.termdebug')
require('config.autopairs')
require('config.neorg')
